### PR TITLE
Pamela

### PR DESCRIPTION
**Pull request by pamolowo**
updated responsiveness on the login
reworked on respomsiveness and folder rearrangement

### CODE REVIEW

**Review by veiled-coder — CHANGES_REQUESTED** [review]
1. Move your css files into a styles folder 

2.  Make your page responsive by using max-width and width (learn more about there usage together) 

3. The page should not be longer than the view port i.e height should be less than 100vh

**_To check responsiveness of a page on all screen sizes ,inspect the web page and click on the overlayed mobile phones beside the **element** tab at the top_**

see the below screenshot for checking responsiveness
login unresponsive

**Comment by pamolowo** [comment]
updated responsiveness on the code

**Review by veiled-coder — CHANGES_REQUESTED** [review]
1. create a styles folder,create your loginForm.css and write all css relating to the login form component

2. create images folder and move all images to that folder
3. images should be removed from the components folder and moved to the images folder 
4. The page is not responsive...kindly use your google hrome dev tools to inspect and view how your page looks like on all screen sizes

**Comment by veiled-coder** [comment]
updated responsiveness on the LoginPage,check it out on the dev branch

**Review by veiled-coder — COMMENTED** [review]
checked

**Pull request closed without merging**
